# Generated by Django 4.2.7 on 2025-05-24 02:13

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('client_ip', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_webhook', models.BooleanField(default=False)),
                ('webhook_endpoint', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
            ],
            options={
                'verbose_name': 'Conexión Activa',
                'verbose_name_plural': 'Conexiones Activas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionCleanupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_connections_before', models.IntegerField()),
                ('inactive_connections_found', models.IntegerField()),
                ('connections_closed', models.IntegerField()),
                ('cleanup_reason', models.TextField()),
                ('connections_closed_list', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Log de Limpieza',
                'verbose_name_plural': 'Logs de Limpieza',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('connection_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_blocked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('backup_connection_count', models.IntegerField(default=1)),
                ('backup_last_seen', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'IP Sospechosa',
                'verbose_name_plural': 'IPs Sospechosas',
                'ordering': ['-connection_count'],
            },
        ),
    ]
